version: "3.7"

services:
  server:
    build: ./
    restart: on-failure
    env_file:
      - prod.env
  postgres:
    build: ./pg
    restart: on-failure
    env_file:
      - ./pg/db.env
    volumes:
      - static_data:/var/lib/postgresql/data/pgdata/
    ports:
      - "5432:5432"

volumes:
  static_data:
