version: "3.7"

services:
  server:
    build: ./
    restart: on-failure
    env_file:
      - .env
  postgres:
    build: ./pg
    restart: on-failure
    env_file:
      - .env
    volumes:
      - static_data:/var/lib/postgresql/data/pgdata/
    ports:
      - "5433:5432"

volumes:
  static_data:
