export const GREETINGS = [
  "que bola",
  "q welta",
  "hablate tankeeeeeeee",
  "q bolon",
  "q welta lokol",
  "q bola chamacón",
  "q welta el mio",
  "hablate chamaco de escuela",
  "un saludos pa la gente de hialeah",
  "q welta los mio",
  "hablate pikete",
  "reportate el mio",
  "te descargo un monton y tu sabe q si",
  "asere te descargo y no te lo mando a decir con andie",
  "q welta chamaco buenoooo",
  "diaz canel singao, ando cerrao",
  "hablateeeeeeeeeeeeeeeeeeee",
  "q welta taigel",
  "hablate tankemiooooooooooooooooooooooooooooooooo",
  "q pinga eh tu sabe q yo me reporto solo",
  "igba igba yentono maferefun orula asere ashe pa ti padrino",
  "hablate matatannnnnnnnnnnnnnnnnnnnnnnn",
];
