export const INSULTS = [
  "es tremendo punto",
  "es tremendo zero a la izquierda",
  "es tremendo anormal",
  "es tremendo fideador",
  "es tremendo baiter",
  "es tremendo bottomfragger",
  "es tremendo mega punto",
  "es un punto",
  "es un zero a la izquierda",
  "es un anormal",
  "es un fideador",
  "es un baiter",
  "es un bottomfragger",
  "es un mega punto",
  "es tremendo clase punto",
  "es tremendo clase zero a la izquierda",
  "es tremendo clase anormal",
  "es tremendo clase fideador",
  "es tremendo clase baiter",
  "es tremendo clase bottomfragger",
  "es un perro punto",
  "es un perro zero a la izquierda",
];
